frontier_exploration_node:
  ros__parameters:
    
    costmap_topic: '/global_costmap/costmap'
    goal_pose_topic: 'desired_pose'
    exploration_status_topic: 'exploration_status'
    
    exploration_rate: 0.5 
    
    min_frontier_size: 15
    frontier_travel_point_ratio: 0.3 
    
    # Options: 'nearest', 'largest', 'information_gain'
    goal_selection_strategy: 'information_gain'
    
    min_distance_to_obstacle: 0.6 
    max_goal_distance: 15.0 
    
    exploration_complete_threshold: 0.92 
    min_free_space_for_completion: 150 